import { Hadith } from './types';

export const VERIFIED_HADITHS: Hadith[] = [
  {
    id: 'abudawud-1555',
    collection: 'Sunan Abi Dawud',
    collection_ar: 'سنن أبي داود',
    hadith_number: 1555,
    narrator_ar: 'أَبِي سَعِيدٍ الْخُدْرِيِّ رَضِيَ اللَّهُ عَنْهُ',
    narrator_en: 'Abu Sa\'id al-Khudri (may Allah be pleased with him)',
    text_ar: 'دَخَلَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ ذَاتَ يَوْمٍ الْمَسْجِدَ فَإِذَا هُوَ بِرَجُلٍ مِنْ الأَنْصَارِ يُقَالُ لَهُ أَبُو أُمَامَةَ، فَقَالَ: «يَا أَبَا أُمَامَةَ، مَا لِي أَرَاكَ جَالِسًا فِي الْمَسْجِدِ فِي غَيْرِ وَقْتِ الصَّلَاةِ؟» قَالَ: هُمُومٌ لَزِمَتْنِي، وَدُيُونٌ يَا رَسُولَ اللَّهِ. قَالَ: «أَفَلَا أُعَلِّمُكَ كَلَامًا إِذَا أَنْتَ قُلْتَهُ أَذْهَبَ اللَّهُ عَزَّ وَجَلَّ هَمَّكَ، وَقَضَى عَنْكَ دَيْنَكَ؟ قُلْ إِذَا أَصْبَحْتَ وَإِذَا أَمْسَيْتَ: اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ الْهَمِّ وَالْحَزَنِ، وَأَعُوذُ بِكَ مِنْ الْعَجْزِ وَالْكَسَلِ، وَأَعُوذُ بِكَ مِنْ الْجُبْنِ وَالْبُخْلِ، وَأَعُوذُ بِكَ مِنْ غَلَبَةِ الدَّيْنِ وَقَهْرِ الرِّجَالِ». قَالَ: فَفَعَلْتُ ذَلِكَ فَأَذْهَبَ اللَّهُ عَزَّ وَجَلَّ هَمِّي، وَقَضَى عَنِّي دَيْنِي.',
    text_en: 'The Messenger of Allah (ﷺ) entered the mosque one day and saw an Ansari man named Abu Umamah. He asked: "Why are you sitting in the mosque outside prayer time?" He replied: "Entangled in worries and debts, O Messenger of Allah." The Prophet said: "Shall I not teach you words which, if you say them, Allah will remove your worry and settle your debt? Say in the morning and evening: O Allah, I seek refuge in You from worry and grief, from incapacity and laziness, from cowardice and miserliness, and from the burden of debt and the oppression of men." Abu Umamah said: "I did so, and Allah removed my worry and settled my debt."',
    grading: 'Authentic (Hasan/Sahih)',
    grading_ar: 'صحيح',
    theme_ar: 'تفريج الهموم وقضاء الديون والسكينة النفسية',
    theme_en: 'Relief of Anxiety, Debt Freedom & Inner Peace',
    life_benefit_ar: 'هذا الدعاء النبوي العظيم يجمع أسباب الحماية النفسية والمالية والعملية، ويعالج ثماني آفات تعطل حياة الإنسان.',
    life_benefit_en: 'This profound prophetic prayer shields the believer from eight core emotional, psychological, and financial hurdles.',
    explanation_ar: 'استعاذ النبي ﷺ من أمهات المنغصات: الهم (لما يستقبل من الأمور) والحزن (على ما فات) والعجز (عدم القدرة) والكسل (عدم الإرادة مع القدرة) والجبن والبخل وغلبة الدين وقهر الرجال (تسلط الظالمين).',
    explanation_en: 'The Prophet sought protection from all root causes of grief, psychological paralysis, financial oppression, and lack of willpower.',
    source_url: 'https://sunnah.com/abudawud:1555'
  },
  {
    id: 'tirmidhi-2346',
    collection: 'Jami` at-Tirmidhi',
    collection_ar: 'جامع الترمذي',
    hadith_number: 2346,
    narrator_ar: 'عُبَيْدِ اللَّهِ بْنِ مِحْصَنٍ الْخَطْمِيِّ رَضِيَ اللَّهُ عَنْهُ',
    narrator_en: 'Ubaidullah bin Mihsan al-Khatmi (may Allah be pleased with him)',
    text_ar: 'قَالَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ: «مَنْ أَصْبَحَ مِنْكُمْ آمِنًا فِي سِرْبِهِ، مُعَافًى فِي جَسَدِهِ، عِنْدَهُ قُوتُ يَوْمِهِ، فَكَأَنَّمَا حِيزَتْ لَهُ الدُّنْيَا بِحَذَافِيرِهَا».',
    text_en: 'The Messenger of Allah (ﷺ) said: "Whoever among you wakes up secure in his dwelling, healthy in his body, having his food for the day, it is as if the whole world has been gathered for him."',
    grading: 'Hasan (Graded Sahih by Al-Albani)',
    grading_ar: 'حسن صحيح',
    theme_ar: 'معادلة السعادة النفسية والامتنان الحقيقي',
    theme_en: 'The True Formula for Psychological Contentment',
    life_benefit_ar: 'يلخص الحديث أركان الطمأنينة الثلاثة: الأمن الداخلي، والعافية الجسدية، وكفاية اليوم الحاضر دون القلق المفرط على المستقبل.',
    life_benefit_en: 'Summarizing the three pillars of true wellbeing: emotional safety, bodily health, and present-day sustenance.',
    explanation_ar: 'من جمع الله له أمن الوطن والنفس، وصحة البدن، ورزق يومه، فقد حاز من الدنيا ما يحتاجه الإنسان لبلوغ السعادة وعبادة ربه بصفاء بال.',
    explanation_en: 'Whoever possesses safety, health, and daily food possesses all that is truly needed for worldly peace and purposeful worship.',
    source_url: 'https://sunnah.com/tirmidhi:2346'
  },
  {
    id: 'bukhari-2078',
    collection: 'Sahih al-Bukhari',
    collection_ar: 'صحيح البخاري',
    hadith_number: 2078,
    narrator_ar: 'أَبِي هُرَيْرَةَ رَضِيَ اللَّهُ عَنْهُ',
    narrator_en: 'Abu Hurairah (may Allah be pleased with him)',
    text_ar: 'عَنِ النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ قَالَ: «كَانَ رَجُلٌ يُدَايِنُ النَّاسَ، فَكَانَ يَقُولُ لِفَتَاهُ: إِذَا أَتَيْتَ مُعْسِرًا فَتَجَاوَزْ عَنْهُ، لَعَلَّ اللَّهَ يَتَجَاوَزُ عَنَّا. فَلَقِيَ اللَّهَ، فَتَجَاوَزَ عَنْهُ».',
    text_en: 'The Prophet (ﷺ) said: "There was a man who used to give loans to the people. He used to say to his servant: If you come to someone in hardship, forgive him his debt, so that Allah may forgive us. When he met Allah, Allah forgave him."',
    grading: 'Authentic (Sahih)',
    grading_ar: 'صحيح متفق عليه',
    theme_ar: 'التسامح مع الناس والتماس العذر للمعسرين',
    theme_en: 'Leniency, Compassion & Overlooking Debts',
    life_benefit_ar: 'الجزاء من جنس العمل؛ من يسّر على معسر أو سامح الناس في معاملاتهم المادية، عامله الله بلطفه وعفوه يوم القيامة.',
    life_benefit_en: 'Divine reciprocity: whoever shows grace and ease to people in distress will receive Allah\'s supreme forgiveness on the Day of Judgment.',
    explanation_ar: 'يبين الحديث أن الرحمة والتيسير في المعاملات المالية والتنازل عن الحقوق للمحتاجين من أعظم أبواب نيل مغفرة الله تعالى ودخول الجنة.',
    explanation_en: 'Demonstrating that financial forbearance and kindness toward struggling debtors is among the greatest pathways to divine mercy.',
    source_url: 'https://sunnah.com/bukhari:2078'
  },
  {
    id: 'muslim-2732',
    collection: 'Sahih Muslim',
    collection_ar: 'صحيح مسلم',
    hadith_number: 2732,
    narrator_ar: 'أَبِي الدَّرْدَاءِ رَضِيَ اللَّهُ عَنْهُ',
    narrator_en: 'Abu ad-Darda\' (may Allah be pleased with him)',
    text_ar: 'قَالَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ: «مَا مِنْ عَبْدٍ مُسْلِمٍ يَدْعُو لأَخِيهِ بِظَهْرِ الْغَيْبِ، إِلاَّ قَالَ الْمَلَكُ: وَلَكَ بِمِثْلٍ».',
    text_en: 'The Messenger of Allah (ﷺ) said: "No Muslim servant prays for his brother behind his back except that the appointed angel says: And for you the same."',
    grading: 'Authentic (Sahih)',
    grading_ar: 'صحيح',
    theme_ar: 'سر الدعاء الصادق للآخرين والملائكة الموكلة',
    theme_en: 'The Secret Power of Praying for Others in Private',
    life_benefit_ar: 'أسرع طريقة لاستجابة دعائك لنفسك هي أن تدعو به لأخيك المسلم بظهر الغيب، فإن الملك يؤمن ويدعو لك بنفس ما دعوت.',
    life_benefit_en: 'The most effective way to have your prayers answered is to sincerely pray for your brothers and sisters in their absence.',
    explanation_ar: 'الدعاء بظهر الغيب علامة على نقاء القلب من الحسد وصدق الأخوة، ولذلك جعل الله له كرامة خاصة بتوكيل ملك كريم يؤمن ويدعو للداعي بالمثل.',
    explanation_en: 'Praying for others without their knowledge proves purity of heart and unconditional goodwill, earning an angelic prayer in return.',
    source_url: 'https://sunnah.com/muslim:2732'
  },
  {
    id: 'silsila-906',
    collection: 'Al-Silsila Al-Sahiha (Al-Albani)',
    collection_ar: 'السلسلة الصحيحة (الألباني)',
    hadith_number: 906,
    narrator_ar: 'عَبْدِ اللَّهِ بْنِ عُمَرَ رَضِيَ اللَّهُ عَنْهُمَا',
    narrator_en: 'Abdullah bin Umar (may Allah be pleased with them)',
    text_ar: 'قَالَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ: «أَحَبُّ النَّاسِ إِلَى اللَّهِ أَنْفَعُهُمْ لِلنَّاسِ، وَأَحَبُّ الأَعْمَالِ إِلَى اللَّهِ سُرُورٌ تُدْخِلُهُ عَلَى مُسْلِمٍ، أَوْ تَكْشِفُ عَنْهُ كُرْبَةً، أَوْ تَقْضِي عَنْهُ دَيْنًا، أَوْ تَطْرُدُ عَنْهُ جُوعًا، وَلأَنْ أَمْشِيَ مَعَ أَخٍ لِي فِي حَاجَةٍ أَحَبُّ إِلَيَّ مِنْ أَنْ أَعْتَكِفَ فِي هَذَا الْمَسْجِدِ شَهْرًا (يَعْنِي مَسْجِدَ الْمَدِينَةِ)».',
    text_en: 'The Messenger of Allah (ﷺ) said: "The most beloved of people to Allah are those who bring most benefit to people, and the most beloved deed to Allah is bringing happiness to a Muslim, relieving his distress, paying off his debt, or warding off his hunger. To walk with a brother to fulfill his need is more beloved to me than staying in retreat (I\'tikaf) in this mosque (the Prophet\'s Mosque in Medina) for a whole month."',
    grading: 'Authentic (Sahih by Al-Albani)',
    grading_ar: 'صحيح',
    theme_ar: 'قضاء حوائج الناس وإدخال السرور على القلوب',
    theme_en: 'Serving People & Spreading Joy in Hearts',
    life_benefit_ar: 'السعي في قضاء حوائج الناس ومساعدتهم يعدل في فضله عبادة الاعتكاف شهراً كاملاً في المسجد النبوي الشريف!',
    life_benefit_en: 'Walking alongside someone to assist them in their need carries immense spiritual merit surpassing a month of retreat in the Prophet\'s Mosque.',
    explanation_ar: 'يوضح النبي ﷺ أن نفع الخلق وإدخال الفرحة عليهم من أجلّ القربات التي يتقرب بها العبد إلى ربه سبحانه وتعالى.',
    explanation_en: 'The Prophet teaches that uplifting society and aiding people in need is one of the highest expressions of faith.',
    source_url: 'https://sunnah.com'
  },
  {
    id: 'muslim-2593',
    collection: 'Sahih Muslim',
    collection_ar: 'صحيح مسلم',
    hadith_number: 2593,
    narrator_ar: 'عَائِشَةَ رَضِيَ اللَّهُ عَنْهَا',
    narrator_en: 'Aisha (may Allah be pleased with her)',
    text_ar: 'قَالَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ: «إِنَّ الرِّفْقَ لَا يَكُونُ فِي شَيْءٍ إِلَّا زَانَهُ، وَلَا يُنْزَعُ مِنْ شَيْءٍ إِلَّا شَانَهُ».',
    text_en: 'The Messenger of Allah (ﷺ) said: "Gentleness is not found in anything except that it beautifies it, and it is not removed from anything except that it mars it."',
    grading: 'Authentic (Sahih)',
    grading_ar: 'صحيح',
    theme_ar: 'سحر الرفق واللين في الحوار والتعاملات',
    theme_en: 'The Transformative Beauty of Gentleness',
    life_benefit_ar: 'التعامل برفق ولين يحل أعقد المشكلات في البيت والعمل والعلاقات، بينما العنف والحدة يفسدان حتى أعدل القضايا.',
    life_benefit_en: 'Applying gentle wisdom and empathy beautifies all personal, professional, and familial interactions.',
    explanation_ar: 'الرفق في الأقوال والأفعال يزين كل تصرف ويكسب القلوب، والغلظة تشوه الأعمال وتورث النفور والعداوة.',
    explanation_en: 'Gentleness in speech and demeanor wins hearts and dignifies actions, while harshness drives people away.',
    source_url: 'https://sunnah.com/muslim:2593'
  },
  {
    id: 'bukhari-6409',
    collection: 'Sahih al-Bukhari',
    collection_ar: 'صحيح البخاري',
    hadith_number: 6409,
    narrator_ar: 'أَبِي هُرَيْرَةَ رَضِيَ اللَّهُ عَنْهُ',
    narrator_en: 'Abu Hurairah (may Allah be pleased with him)',
    text_ar: 'قَالَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ: «كَلِمَتَانِ خَفِيفَتَانِ عَلَى اللِّسَانِ، ثَقِيلَتَانِ فِي الْمِيزَانِ، حَبِيبَتَانِ إِلَى الرَّحْمَنِ: سُبْحَانَ اللَّهِ وَبِحَمْدِهِ، سُبْحَانَ اللَّهِ الْعَظِيمِ».',
    text_en: 'The Messenger of Allah (ﷺ) said: "Two words that are light on the tongue, heavy in the scale, and beloved to the Most Merciful: Subhan Allahi wa bihamdihi (Glory be to Allah and praise Him), Subhan Allahil-Azim (Glory be to Allah the Almighty)."',
    grading: 'Authentic (Sahih)',
    grading_ar: 'صحيح متفق عليه',
    theme_ar: 'الذكر اليومي الخفيف عظيم الأجر والمحبة',
    theme_en: 'Light Daily Remembrance with Enormous Scales',
    life_benefit_ar: 'استثمار أوقات الانتظار والتنقل بترديد هاتين الكلمتين كنز حقيقي يثقل ميزان حسناتك يوم الحساب.',
    life_benefit_en: 'Investing spare daily moments repeating these two phrases infuses your day with divine love and heavy good deeds.',
    explanation_ar: 'هذا الحديث هو خاتمة صحيح البخاري، يبين سعة فضل الله حيث يجزي على العمل القصير الخفيف الجزاء الأوفى العظيم.',
    explanation_en: 'This famous closing narration of Sahih al-Bukhari illustrates Allah\'s infinite generosity for simple sincere words of praise.',
    source_url: 'https://sunnah.com/bukhari:6409'
  }
];

export async function fetchDailyHadith(index: number = 0): Promise<Hadith> {
  const safeIndex = Math.abs(index) % VERIFIED_HADITHS.length;
  return VERIFIED_HADITHS[safeIndex];
}
